### ISSUE TITLE
feature request: Jump from google doc page to the corresponding gdoc wiki page.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/gdocwiki#10]
![image](https://user-images.githubusercontent.com/30543181/118102851-dcfadc80-b40b-11eb-9fca-d249ab97d9e5.png)

I want to have a button/extension feature/shortcut to jump to the corresponding gdoc wiki page.

**Comment by gregwebs** [comment]
PR #40 has an icon for the link

**Comment by gregwebs** [comment]
Try the latest browser extension now.
