### ISSUE TITLE
Opening docs in new tabs requires signing in

### ISSUE THREAD

**Issue by ekexium** [pingcap/gdocwiki#8]
If I "open link in a new tab", the error occurred:
```
Failed to load content: File not found: xxxx
You may need to sign-in to view the content.
```

And I need to click "Sign in" every time.

Can we improve this?

**Comment by breeswish** [comment]
Thanks for the report! Actually gdocwiki shares the cookie for all domains, so that this sign-in is not needed if you open in a new window, or even close the browser and open again. Could you checkout whether you have blocked cookie storage or something similar?

**Comment by ekexium** [comment]
Confirmed it's caused by "prevent cross-site tracking" in Safari and the Ghostery plugin in Firefox.
I'd rather not change these settings, so I hope it can be improved in another way if possible.

**Comment by breeswish** [comment]
How about adding whitelist domains? :) As you can inspect from the source code we do not have any trackers. We do have cross-site cookies, and which is exactly used for keeping sessions.

**Comment by SunRunAway** [comment]
Safari has no whitelist domains for "prevent cross-site tracking". Is it possible to have any methods to impove? @breeswish
