### ISSUE TITLE
chrome extension: click to notify owner of off-tree docs

### ISSUE THREAD

**Issue by dragonly** [pingcap/gdocwiki#9]
When I open an off-tree doc, and I am not the owner, then there's nothing added on page by the extension.
I suggest to add a feature to notify the owner, where I can leave a note and ask he/she to add this doc to a tree/directory, which will greatly help the convergence of the wiki.

Possible implementation:
1. Call google API to find the creator/commenters of this doc.
2. When click the extension icon, pop up an email-sending-box-like modal page, add the creator as the receiver, cc commenters, and use "I found this doc is out of the wiki tree. I suggest we put it at <path/to/wiki/directory>".
3. Call registered sending API (Slack/E-mail/Feishu/etc).

**Comment by gregwebs** [comment]
What I am doing with #24 is just leaving a comment at the top of the doc asking to move the file to a shared directory. This will cause the doc owner and others to receive an email notification. The email can serve as a TODO and the comment is a reminder on the doc itself. @dragonly do you think this is a good solution or is it too noisy?

**Comment by gregwebs** [comment]
I also added a button that can be clicked to attach a comment to the doc itself (not any particular text).

**Comment by gregwebs** [comment]
@dragonly @breeswish  can we close this issue now?

**Comment by gregwebs** [comment]
Try the latest browser extension noiw.
